#!/bin/bash

echo "📦 FunClip iOS - Dependency Setup Guide"
echo "======================================="
echo ""
echo "Your Supabase credentials have been configured:"
echo "✅ URL: https://ivyftvzkswuoavsfaplk.supabase.co"
echo "✅ API Key: Configured in AppConfig.swift"
echo ""
echo "To add Supabase to your Xcode project:"
echo ""
echo "1. Open Xcode:"
echo "   open FunClipApp.xcodeproj"
echo ""
echo "2. Add Swift Package Dependencies:"
echo "   • File → Add Package Dependencies..."
echo "   • Enter: https://github.com/supabase/supabase-swift"
echo "   • Version: Up to Next Major 2.0.0"
echo "   • Click 'Add Package'"
echo "   • Select these products:"
echo "     ✅ Supabase"
echo "     ✅ Auth"
echo "     ✅ Realtime"
echo "     ✅ Storage"
echo ""
echo "3. (Optional) Add Kingfisher for image loading:"
echo "   • File → Add Package Dependencies..."
echo "   • Enter: https://github.com/onevcat/Kingfisher"
echo "   • Version: Up to Next Major 7.0.0"
echo ""
echo "4. Build and Run:"
echo "   • Press ⌘+B to build"
echo "   • Press ⌘+R to run"
echo ""
echo "✨ Your app is configured and ready to authenticate with Supabase!"
echo ""
echo "Test credentials for development:"
echo "Email: test@example.com"
echo "Password: Test123456"
echo ""
echo "Note: Sign in with Apple requires Apple Developer account configuration."